import { IsString, Length, Matches } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

/**
 * Body of `POST /clients/requests/accept-by-token`. Tokens are
 * generated by the backend (`crypto.randomBytes(32).toString('hex')`
 * → 64 hex chars). We enforce the exact shape so attackers can't
 * smuggle arbitrary strings into the lookup path.
 */
export class AcceptByTokenDto {
  @ApiProperty({
    example: 'a1b2c3d4e5f6...64hex',
    description: 'Invitation token from the referral link.',
  })
  @IsString()
  @Length(32, 128)
  @Matches(/^[a-zA-Z0-9_-]+$/, {
    message: 'token must be hex/url-safe characters only',
  })
  token: string;
}
