import {
  Table,
  Column,
  Model,
  DataType,
  ForeignKey,
  BelongsTo,
  CreatedAt,
  UpdatedAt,
} from 'sequelize-typescript';
import { User } from '../../user/entities/user.entity';
import { Subscription } from './subscription.entity';

/**
 * Invoice status values — mapped 1:1 from Stripe invoice statuses.
 *
 * Lifecycle:
 *   draft         → created but not finalized, can still be edited
 *   open          → finalized, waiting for payment
 *   paid          → fully paid (by card OR marked paid out of band)
 *   void          → voided before payment; CANNOT void a paid invoice
 *   uncollectible → declared uncollectible (rare, manual)
 */
export enum InvoiceStatus {
  DRAFT = 'draft',
  OPEN = 'open',
  PAID = 'paid',
  VOID = 'void',
  UNCOLLECTIBLE = 'uncollectible',
}

/**
 * Invoice Entity
 *
 * Local mirror of a Stripe Invoice — the source-of-truth record for
 * every charge an instructor issues, whether it's a one-off or a
 * subscription-generated invoice.
 *
 * Field groups:
 *
 * Money:
 *   amountDueCents       — what the client was billed
 *   amountPaidCents      — what was actually collected
 *   amountRemainingCents — for partial payments
 *   applicationFeeCents  — the platform fee we took (0 today)
 *
 * Stripe hosted assets — iframe / link these straight from the UI:
 *   hostedInvoiceUrl — Stripe's fully-hosted branded invoice page
 *   invoicePdf       — downloadable PDF, generated by Stripe
 *
 * Manual payment support:
 *   paidOutOfBand — TRUE when the instructor marked the invoice as
 *                   paid via cash / bank transfer. Stripe supports
 *                   this natively via `invoices.pay({ paid_out_of_band: true })`
 *                   — no fees, invoice flips to 'paid' status, no
 *                   PaymentIntent is created.
 *
 * EU legal (Romanian OUG 34/2014):
 *   requiresImmediateAccessWaiver — TRUE when the service starts
 *                                    immediately on payment (e.g. a
 *                                    same-day PT session). Forces the
 *                                    client to tick a consent box at
 *                                    checkout.
 *   waiverAcceptedAt              — timestamp the waiver was accepted
 *                                    (the full audit trail lives in
 *                                    payment_consent).
 *
 * Invoice editing rules (enforced in service layer):
 *   - Cannot void a 'paid' invoice — to reverse, issue a refund.
 *   - Cannot edit a finalized invoice — use "void & recreate" flow.
 */
@Table({
  tableName: 'invoice',
  timestamps: true,
  underscored: true,
})
export class Invoice extends Model {
  @Column({
    type: DataType.CHAR(36),
    defaultValue: DataType.UUIDV4,
    primaryKey: true,
  })
  declare id: string;

  @ForeignKey(() => User)
  @Column({
    type: DataType.CHAR(36),
    allowNull: false,
  })
  declare instructorId: string;

  /**
   * Nullable — guests invoiced by email only have no clientId.
   */
  @ForeignKey(() => User)
  @Column({
    type: DataType.CHAR(36),
    allowNull: true,
  })
  declare clientId: string | null;

  @Column({
    type: DataType.STRING(255),
    allowNull: false,
  })
  declare stripeCustomerId: string;

  /**
   * NULL for one-off invoices. Set for subscription-generated
   * invoices (the "billing cycle" invoice).
   */
  @ForeignKey(() => Subscription)
  @Column({
    type: DataType.CHAR(36),
    allowNull: true,
  })
  declare subscriptionId: string | null;

  @Column({
    type: DataType.STRING(255),
    allowNull: false,
  })
  declare stripeInvoiceId: string;

  /**
   * Stripe-assigned human-readable invoice number (e.g. `ACB-0001`).
   * Per-account globally incrementing. NULL until finalization.
   */
  @Column({
    type: DataType.STRING(100),
    allowNull: true,
  })
  declare number: string | null;

  @Column({
    type: DataType.STRING(30),
    allowNull: false,
    validate: { isIn: [Object.values(InvoiceStatus)] },
  })
  declare status: InvoiceStatus;

  @Column({
    type: DataType.INTEGER,
    allowNull: false,
  })
  declare amountDueCents: number;

  @Column({
    type: DataType.INTEGER,
    allowNull: false,
    defaultValue: 0,
  })
  declare amountPaidCents: number;

  @Column({
    type: DataType.INTEGER,
    allowNull: false,
    defaultValue: 0,
  })
  declare amountRemainingCents: number;

  @Column({
    type: DataType.STRING(3),
    allowNull: false,
  })
  declare currency: string;

  /**
   * Platform fee actually collected on this invoice. May be 0 even
   * when the instructor's platformFeeBps is non-zero (e.g. because
   * the invoice was marked paidOutOfBand).
   */
  @Column({
    type: DataType.INTEGER,
    allowNull: false,
    defaultValue: 0,
  })
  declare applicationFeeCents: number;

  @Column({
    type: DataType.DATE,
    allowNull: true,
  })
  declare dueDate: Date | null;

  @Column({
    type: DataType.DATE,
    allowNull: true,
  })
  declare finalizedAt: Date | null;

  @Column({
    type: DataType.DATE,
    allowNull: true,
  })
  declare paidAt: Date | null;

  @Column({
    type: DataType.DATE,
    allowNull: true,
  })
  declare voidedAt: Date | null;

  /**
   * Stripe's fully hosted, fully branded invoice page. Safe to iframe
   * (Stripe serves it with `X-Frame-Options: ALLOWALL`).
   */
  @Column({
    type: DataType.TEXT,
    allowNull: true,
  })
  declare hostedInvoiceUrl: string | null;

  /**
   * Direct PDF download URL, generated by Stripe. We do NOT generate
   * PDFs ourselves.
   */
  @Column({
    type: DataType.TEXT,
    allowNull: true,
  })
  declare invoicePdf: string | null;

  @Column({
    type: DataType.BOOLEAN,
    allowNull: false,
    defaultValue: false,
  })
  declare paidOutOfBand: boolean;

  @Column({
    type: DataType.TEXT,
    allowNull: true,
  })
  declare description: string | null;

  /**
   * Arbitrary JSONB metadata — we store things like
   * `{ sessionId, groupId }` so invoices can link back to the
   * BeeActive entities they relate to.
   */
  @Column({
    type: DataType.JSONB,
    allowNull: true,
  })
  declare metadata: Record<string, unknown> | null;

  @Column({
    type: DataType.BOOLEAN,
    allowNull: false,
    defaultValue: false,
  })
  declare requiresImmediateAccessWaiver: boolean;

  @Column({
    type: DataType.DATE,
    allowNull: true,
  })
  declare waiverAcceptedAt: Date | null;

  @CreatedAt
  declare createdAt: Date;

  @UpdatedAt
  declare updatedAt: Date;

  // Relationships
  @BelongsTo(() => User, 'instructorId')
  declare instructor: User;

  @BelongsTo(() => User, 'clientId')
  declare client: User | null;

  @BelongsTo(() => Subscription, 'subscriptionId')
  declare subscription: Subscription | null;
}
